#@ load("@ytt:data", "data")
---
#@ if data.values.traefik.custom_cert:
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: traefik-cert
spec:
  # Secret names are always required.
  secretName: traefik-cert
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  #subject:
  #  organizations:
  #  - jetstack
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  #commonName: example.com
  isCA: false
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  #@ for domain in data.values.traefik.cert_domains:
  - #@ domain
  #@ end
  #uris:
  #- spiffe://cluster.local/ns/sandbox/sa/example
  #ipAddresses:
  #- 192.168.0.5
  # Issuer references are always required.
  issuerRef:
    #@ if data.values.traefik.production_cert:
    name: letsencrypt-production
    #@ else:
    name: letsencrypt-staging
    #@ end
    # We can reference ClusterIssuers by changing the kind here.
    # The default value is Issuer (i.e. a locally namespaced Issuer)
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    # group: cert-manager.io
#---
#apiVersion: traefik.containo.us/v1alpha1
#kind: TLSStore
#metadata:
#  name: default
#  namespace: #@ data.values.traefik.namespace
#spec:
#  defaultCertificate:
#    secretName: traefik-cert
#@ end
